# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-25 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='streetaddress2',
            new_name='street_address2',
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='Aled Griffiths', max_length=50),
        ),
    ]
