# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.CharField(choices=[('europe', 'Europe'), ('america', 'America'), ('rest_of_world', 'Rest_Of_World')], default='europe', max_length=13),
        ),
    ]
